<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Nishchay" failures="1" tests="5" name="Personal Loan" time="0.056" errors="0" timestamp="2024-05-12T16:54:38 IST">
  <testcase classname="test1.day1" name="Demo" time="0.009">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test1.day1.Demo(day1.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test1.day2" name="ploan" time="0.002"/>
  <testcase classname="test1.day4" name="ApiLoginHomeLoan" time="0.002"/>
  <testcase classname="test1.day4" name="MobileLoginHomeLoan" time="0.002"/>
  <testcase classname="test1.day4" name="WebLoginHomeLoan" time="0.003"/>
  <testcase classname="test1.day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal Loan -->
